from __future__ import annotations

from typing import TYPE_CHECKING, Any

from .intent import normalize_visual_text
from .schema import (
    ChartPlan,
    ChartPlanningInput,
    ChartSpec,
    ChartType,
    ChartWarning,
    ExpectedResultShape,
    VisualizationIntent,
)

if TYPE_CHECKING:
    from health_system_chatbot.config import ChatbotConfig
    from health_system_chatbot.models import RetrievedContext


MAX_BAR_CATEGORIES = 30
MAX_PIE_CATEGORIES = 8


def build_chart_plan(
    *,
    question: str,
    intent: VisualizationIntent,
    context: "RetrievedContext | None" = None,
    config: "ChatbotConfig | None" = None,
    allow_llm: bool = True,
) -> ChartPlan:
    if not intent.requested:
        return ChartPlan(requested=False, reason="visualization not requested")

    if (
        allow_llm
        and config is not None
        and config.agent_framework == "pydantic_ai"
        and config.has_openai_key
    ):
        try:
            from health_system_chatbot.agent_deps import ChartDeps
            from health_system_chatbot.agents import build_chart_plan_agent

            agent = build_chart_plan_agent(config)
            deps = ChartDeps(
                config=config,
                question=question,
                visualization_intent=intent,
                retrieved_context=context,
            )
            result = agent.run_sync(_chart_plan_prompt(question, intent, context), deps=deps)
            return _normalize_chart_plan(result.output, question=question, intent=intent)
        except Exception:
            pass

    return _deterministic_chart_plan(question=question, intent=intent)


def _chart_plan_prompt(
    question: str,
    intent: VisualizationIntent,
    context: "RetrievedContext | None",
) -> str:
    tables = ", ".join(context.tables[:12]) if context else ""
    columns = ", ".join(context.columns[:80]) if context else ""
    metrics = (
        "; ".join(f"{metric.name}: {metric.description}" for metric in context.business_metrics[:8])
        if context
        else ""
    )
    return (
        "Planeje um grafico para a pergunta usando um ChartPlan estruturado.\n"
        "Nao gere SQL. Escolha chart_type='auto' se o tipo depender melhor do shape final.\n\n"
        f"Pergunta original: {question}\n"
        f"Pergunta analitica limpa: {intent.analysis_question}\n"
        f"Hint de grafico: {intent.chart_hint}\n"
        f"Tabelas recuperadas: {tables}\n"
        f"Colunas recuperadas: {columns}\n"
        f"Metricas de negocio: {metrics}\n"
    )


def _normalize_chart_plan(
    plan: ChartPlan,
    *,
    question: str,
    intent: VisualizationIntent,
) -> ChartPlan:
    fallback = _deterministic_chart_plan(question=question, intent=intent)
    if not plan.requested:
        plan.requested = True
    if plan.chart_type == "auto" and intent.chart_hint != "auto":
        plan.chart_type = intent.chart_hint
    if not plan.metric:
        plan.metric = fallback.metric
    if not plan.x_dimension:
        plan.x_dimension = fallback.x_dimension
    if not plan.y_column:
        plan.y_column = fallback.y_column
    if not plan.expected_result_shape or plan.expected_result_shape == "unknown":
        plan.expected_result_shape = fallback.expected_result_shape
    if not plan.required_columns:
        plan.required_columns = _required_columns(
            plan.x_dimension,
            plan.y_column,
            plan.series_dimension,
            plan.expected_result_shape,
        )
    if not plan.sql_shape_guidance:
        plan.sql_shape_guidance = _shape_guidance(
            x_dimension=plan.x_dimension,
            y_column=plan.y_column,
            series_dimension=plan.series_dimension,
            expected_shape=plan.expected_result_shape,
        )
    if not plan.reason:
        plan.reason = "chart plan generated by Pydantic AI"
    return plan


def _deterministic_chart_plan(*, question: str, intent: VisualizationIntent) -> ChartPlan:
    text = normalize_visual_text(f"{question} {intent.analysis_question}")
    metric, y_column = _infer_metric(text)
    x_dimension = _infer_x_dimension(text)
    series_dimension = _infer_series_dimension(text, x_dimension=x_dimension)
    chart_type = _infer_chart_type(text, intent.chart_hint, x_dimension, series_dimension)
    expected_shape = _expected_shape(chart_type, x_dimension, series_dimension)
    return ChartPlan(
        requested=True,
        chart_type=chart_type,
        metric=metric,
        x_dimension=x_dimension,
        y_column=y_column,
        series_dimension=series_dimension,
        expected_result_shape=expected_shape,
        required_columns=_required_columns(x_dimension, y_column, series_dimension, expected_shape),
        sql_shape_guidance=_shape_guidance(
            x_dimension=x_dimension,
            y_column=y_column,
            series_dimension=series_dimension,
            expected_shape=expected_shape,
        ),
        reason="deterministic chart plan fallback",
    )


def _infer_metric(text: str) -> tuple[str, str]:
    if any(token in text for token in ("morte", "mortes", "obito", "obitos")):
        return "mortes", "mortes"
    if any(token in text for token in ("valor", "custo", "custos", "faturamento", "receita")):
        return "valor_total", "valor_total"
    if any(token in text for token in ("taxa", "percentual", "porcentagem")):
        return "taxa", "taxa"
    if any(token in text for token in ("media", "média", "permanencia", "permanência")):
        return "media", "media"
    return "internacoes", "internacoes"


def _infer_x_dimension(text: str) -> str | None:
    dimension_terms = (
        ("ano", ("ano", "anos", "evolucao", "evolução", "temporal", "serie", "série")),
        ("sexo", ("sexo", "homens", "mulheres", "masculino", "feminino")),
        ("raca_cor", ("raca", "raça", "cor")),
        ("municipio", ("municipio", "município", "cidade", "cidades")),
        ("uf", ("uf", "estado", "estados")),
        ("diagnostico", ("diagnostico", "diagnóstico", "cid", "causa", "causas")),
        ("carater_internacao", ("carater", "caráter")),
        ("complexidade", ("complexidade",)),
        ("hospital", ("hospital", "hospitais", "estabelecimento")),
    )
    for dimension, terms in dimension_terms:
        if any(term in text for term in terms):
            return dimension
    return None


def _infer_series_dimension(text: str, *, x_dimension: str | None) -> str | None:
    if x_dimension == "ano":
        if any(term in text for term in ("por sexo", "homens e mulheres", "masculino e feminino")):
            return "sexo"
        if any(term in text for term in ("mama e prostata", "mama e próstata")):
            return "diagnostico"
    return None


def _infer_chart_type(
    text: str,
    hint: ChartType,
    x_dimension: str | None,
    series_dimension: str | None,
) -> ChartType:
    if hint != "auto":
        return hint
    if "kpi" in text or "indicador" in text or not x_dimension:
        return "kpi"
    if x_dimension == "ano" or series_dimension:
        return "line"
    if any(term in text for term in ("proporcao", "proporção", "participacao", "participação")):
        return "pie"
    return "bar"


def _expected_shape(
    chart_type: ChartType,
    x_dimension: str | None,
    series_dimension: str | None,
) -> ExpectedResultShape:
    if chart_type == "kpi" or not x_dimension:
        return "single_metric"
    if chart_type == "scatter":
        return "scatter_metric"
    if x_dimension == "ano" and series_dimension:
        return "time_series_metric"
    if x_dimension == "ano":
        return "time_metric"
    return "category_metric"


def _required_columns(
    x_dimension: str | None,
    y_column: str | None,
    series_dimension: str | None,
    expected_shape: ExpectedResultShape,
) -> list[str]:
    columns: list[str] = []
    if expected_shape != "single_metric" and x_dimension:
        columns.append(x_dimension)
    if series_dimension:
        columns.append(series_dimension)
    if y_column:
        columns.append(y_column)
    return list(dict.fromkeys(columns))


def _shape_guidance(
    *,
    x_dimension: str | None,
    y_column: str | None,
    series_dimension: str | None,
    expected_shape: ExpectedResultShape,
) -> str:
    if expected_shape == "single_metric":
        return f"Return a single numeric metric column named {y_column or 'valor'}."
    parts = [part for part in (x_dimension, series_dimension, y_column) if part]
    guidance = "Return only chart-ready columns: " + ", ".join(parts) + "."
    if x_dimension == "ano":
        guidance += " Use one row per year and ORDER BY ano."
    if x_dimension == "sexo" or series_dimension == "sexo":
        guidance += " Return human-readable sex labels, not raw SEXO codes."
    if series_dimension:
        guidance += " Prefer tidy/long format with one row per x dimension and series."
    return guidance


def plan_chart(planning_input: ChartPlanningInput | dict[str, Any]) -> ChartSpec:
    chart_input = (
        planning_input
        if isinstance(planning_input, ChartPlanningInput)
        else ChartPlanningInput.model_validate(planning_input)
    )
    if chart_input.row_count == 0 or not chart_input.rows:
        return ChartSpec(
            chartable=False,
            chart_type="table",
            reason="Resultado vazio; nao ha dados para visualizacao.",
            warnings=[
                ChartWarning(
                    code="empty_result",
                    message="Resultado vazio; grafico nao foi gerado.",
                    severity="info",
                )
            ],
        )

    spec = _spec_from_plan(chart_input)
    if spec is not None:
        return spec
    return _spec_from_shape(chart_input)


def _spec_from_plan(chart_input: ChartPlanningInput) -> ChartSpec | None:
    plan = chart_input.chart_plan
    if not plan or not plan.requested:
        return None
    columns = chart_input.columns
    lookup = {column.lower(): column for column in columns}
    x = _resolve_column(plan.x_dimension, lookup)
    y = _resolve_column(plan.y_column, lookup)
    series = _resolve_column(plan.series_dimension, lookup)
    chart_type = plan.chart_type
    if chart_type == "auto":
        chart_type = _chart_type_from_columns(chart_input, x=x, y=y, series=series)
    if plan.expected_result_shape == "single_metric" or chart_type == "kpi":
        y = y or _first_numeric_column(chart_input)
        if not y:
            return None
        return ChartSpec(
            chartable=True,
            chart_type="kpi",
            title=_title(y),
            y=y,
            encoding={"y_type": "quantitative"},
            data=chart_input.rows[:1],
            reason="Resultado escalar numerico.",
            warnings=_base_warnings(chart_input),
        )
    if not x or not y:
        return None
    return _build_xy_spec(
        chart_input,
        chart_type=chart_type if chart_type != "auto" else "bar",
        x=x,
        y=y,
        series=series,
        reason="Grafico planejado a partir de ChartPlan estruturado.",
    )


def _spec_from_shape(chart_input: ChartPlanningInput) -> ChartSpec:
    numeric = [
        column for column in chart_input.columns if chart_input.column_types.get(column) == "number"
    ]
    temporal = [
        column for column in chart_input.columns if chart_input.column_types.get(column) == "temporal"
    ]
    categorical = [
        column
        for column in chart_input.columns
        if chart_input.column_types.get(column) in {"string", "boolean", "unknown"}
    ]
    if len(chart_input.columns) == 1 and numeric:
        return ChartSpec(
            chartable=True,
            chart_type="kpi",
            title=_title(numeric[0]),
            y=numeric[0],
            encoding={"y_type": "quantitative"},
            data=chart_input.rows[:1],
            reason="Resultado escalar numerico.",
            warnings=_base_warnings(chart_input),
        )
    if len(chart_input.rows) == 1 and len(numeric) >= 2:
        rows = [{"metrica": _humanize(column), "valor": chart_input.rows[0].get(column)} for column in numeric]
        return ChartSpec(
            chartable=True,
            chart_type="bar",
            title="Comparacao de metricas",
            x="metrica",
            y="valor",
            encoding={"x_type": "nominal", "y_type": "quantitative"},
            data=rows,
            reason="Resultado escalar com multiplas metricas numericas.",
            warnings=_base_warnings(chart_input),
        )
    if temporal and numeric:
        series = categorical[0] if categorical else None
        chart_type: ChartType = "area" if chart_input.chart_hint == "area" else "line"
        return _build_xy_spec(
            chart_input,
            chart_type=chart_type,
            x=temporal[0],
            y=numeric[0],
            series=series,
            reason="Resultado temporal com metrica numerica.",
        )
    if categorical and numeric:
        chart_type = chart_input.chart_hint if chart_input.chart_hint in {"pie", "donut"} else "bar"
        return _build_xy_spec(
            chart_input,
            chart_type=chart_type,
            x=categorical[0],
            y=numeric[0],
            series=None,
            reason="Resultado categorico com metrica numerica.",
        )
    return ChartSpec(
        chartable=False,
        chart_type="table",
        data=chart_input.rows[:50],
        reason="Resultado nao possui shape visual confiavel; use tabela.",
        warnings=[
            ChartWarning(
                code="unsupported_shape",
                message="Nao foi possivel inferir eixos de grafico a partir do resultado.",
            )
        ],
    )


def _build_xy_spec(
    chart_input: ChartPlanningInput,
    *,
    chart_type: ChartType,
    x: str,
    y: str,
    series: str | None,
    reason: str,
) -> ChartSpec:
    render_type = "line" if chart_type == "auto" else chart_type
    if render_type == "table":
        return ChartSpec(chartable=False, chart_type="table", data=chart_input.rows, reason=reason)
    category_count = len({row.get(x) for row in chart_input.rows if row.get(x) is not None})
    warnings = _base_warnings(chart_input)
    if render_type in {"pie", "donut"} and category_count > MAX_PIE_CATEGORIES:
        warnings.append(
            ChartWarning(
                code="too_many_categories",
                message=(
                    f"Grafico {render_type} exige poucas categorias; resultado possui "
                    f"{category_count} categorias."
                ),
            )
        )
        return ChartSpec(
            chartable=False,
            chart_type="table",
            data=chart_input.rows[:50],
            reason="Alta cardinalidade para grafico de proporcao.",
            warnings=warnings,
        )
    if render_type == "bar" and category_count > MAX_BAR_CATEGORIES:
        warnings.append(
            ChartWarning(
                code="high_cardinality",
                message=f"Grafico de barras possui {category_count} categorias; considere filtrar.",
            )
        )
    x_type = chart_input.column_types.get(x)
    return ChartSpec(
        chartable=True,
        chart_type=render_type,  # type: ignore[arg-type]
        title=_title(y, x),
        x=x,
        y=y,
        series=series,
        encoding={
            "x_type": "temporal" if x_type == "temporal" else "nominal",
            "y_type": "quantitative",
            **({"series_type": "nominal"} if series else {}),
        },
        data=chart_input.rows,
        reason=reason,
        warnings=warnings,
    )


def _chart_type_from_columns(
    chart_input: ChartPlanningInput,
    *,
    x: str | None,
    y: str | None,
    series: str | None,
) -> ChartType:
    if not x or not y:
        return "kpi"
    if chart_input.column_types.get(x) == "temporal" or series:
        return "line"
    if chart_input.chart_hint in {"pie", "donut", "scatter", "area", "bar", "line"}:
        return chart_input.chart_hint
    return "bar"


def _resolve_column(name: str | None, lookup: dict[str, str]) -> str | None:
    if not name:
        return None
    lowered = name.lower()
    if lowered in lookup:
        return lookup[lowered]
    for key, value in lookup.items():
        if lowered in key or key in lowered:
            return value
    return None


def _first_numeric_column(chart_input: ChartPlanningInput) -> str | None:
    for column in chart_input.columns:
        if chart_input.column_types.get(column) == "number":
            return column
    return None


def _base_warnings(chart_input: ChartPlanningInput) -> list[ChartWarning]:
    warnings: list[ChartWarning] = []
    if chart_input.truncated:
        warnings.append(
            ChartWarning(
                code="truncated_result",
                message="Resultado truncado antes da geracao do grafico.",
            )
        )
    return warnings


def _title(y: str, x: str | None = None) -> str:
    if x:
        return f"{_humanize(y)} por {_humanize(x)}"
    return _humanize(y)


def _humanize(value: str) -> str:
    return value.replace("_", " ").strip().lower()

